#ifndef DRAWNODE_H
#define DRAWNODE_H

#include <QVector>
#include <QPointF>
#include "gp/Node.h"

/**
 * Generated by {@link DrawTree}.
 * Represents a drawable tree.
 */
class DrawNode
{
public:
    /**
     * Constructs the node.
     * @param node Node to represent.
     * @param parent Parent of this node.
     * @param depth Depth of this node, starting from 0 being root.
     * @param number The number of the node.
     */
    DrawNode(Node *node, DrawNode *parent = NULL, int depth = 0, int number = 1);

    /** Destroys the node and its children recursively. */
    ~DrawNode();

    /**
     * @return The represented node.
     */
    Node *getNode() { return node; }

    /**
     * @return The x position of this node.
     */
    float getX() { return x; }

    /**
     * @return The y position of this node.
     */
    float getY() { return y; }

    /**
     * @return The children of this node.
     */
    QVector<DrawNode *> getChildren() { return children; }

    /**
     * @return The width of this subtree, including child nodes.
     */
    float getWidth();

    /**
     * @return The height of this subtree, including child nodes.
     */
    float getHeight();

    /**
     * @return The horizontal bounds of this subtree, including child nodes.
     */
    QPointF getBoundsH();

    /**
     * @return The vertial bounds of this subtree, including child nodes.
     */
    QPointF getBoundsV();

    /**
     * Get a child node by its index, using depth-first numbering from 0.
     * @param index The index of the desired node.
     * @return The desired node.
     */
    DrawNode *getNode(int index);

private:
    /**
     * @return The left sibling of this node.
     */
    DrawNode *leftSibling();

    /**
     * @return The leftmost sibling of this node.
     */
    DrawNode *getLeftmostSibling();

    /**
     * @return The next right node.
     */
    DrawNode *nextRight();

    /**
     * @return The next left node.
     */
    DrawNode *nextLeft();

    float x; /**< X position of this node. */
    float y; /**< Y position of this node. */
    QVector<DrawNode *> children; /**< Children of this node. */
    DrawNode *parent; /**< Parent of this node. */
    DrawNode *thread; /**< Thread of this node. */
    DrawNode *ancestor; /**< Ancestor of this node. */
    float offset; /**< Offset of this node. */
    float change; /**< Change for this node. */
    float shift; /**< Amount of shift to apply to this node. */
    float mod; /**< Modifier to apply to this node. */
    int number; /**< Number of this node. */
    Node *node; /**< Represented node. */

    friend class DrawTreeBuilder;
};

#endif // DRAWNODE_H
